name: pgfenicsx_sphinx
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - accessible-pygments=0.0.5=pyhd8ed1ab_1
  - alabaster=1.0.0=pyhd8ed1ab_1
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - brotli-python=1.2.0=py314hdfeb8a1_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py314h4a8dc5f_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - docutils=0.21.2=pyhd8ed1ab_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - ld_impl_linux-64=2.45=bootstrap_ha15bf96_3
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libzlib=1.3.1=hb9d3cd8_2
  - markupsafe=3.0.3=pyh7db6752_0
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pip=25.3=pyh145f28c_0
  - pycparser=2.22=pyh29332c3_1
  - pydata-sphinx-theme=0.16.1=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.14.0=h32b2ec7_102_cp314
  - python_abi=3.14=8_cp314
  - pytz=2025.2=pyhd8ed1ab_0
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - roman-numerals-py=3.1.0=pyhd8ed1ab_0
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - soupsieve=2.8=pyhd8ed1ab_0
  - sphinx=8.2.3=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - tk=8.6.13=noxft_ha0e22de_103
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - zstandard=0.25.0=py314h0f05182_1
  - zstd=1.5.7=hb8e6e7a_2
prefix: /home/moritz/miniconda3/envs/pgfenicsx_sphinx
